name: CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t tour-project .

      # Optionally, run the container to test
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name tour-test tour-project

      # Optionally, stop and remove container after testing
      - name: Clean up container
        run: |
          docker stop tour-test
          docker rm tour-test
